// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMeetingInstance(arg1) {
  return window['go']['main']['App']['AddMeetingInstance'](arg1);
}

export function AddToSemanticIndex(arg1, arg2) {
  return window['go']['main']['App']['AddToSemanticIndex'](arg1, arg2);
}

export function CreateMeeting(arg1, arg2) {
  return window['go']['main']['App']['CreateMeeting'](arg1, arg2);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteMeeting(arg1) {
  return window['go']['main']['App']['DeleteMeeting'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetInstances(arg1) {
  return window['go']['main']['App']['GetInstances'](arg1);
}

export function GetMeetings(arg1) {
  return window['go']['main']['App']['GetMeetings'](arg1);
}

export function GetModelStatus() {
  return window['go']['main']['App']['GetModelStatus']();
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetPriorityTasks() {
  return window['go']['main']['App']['GetPriorityTasks']();
}

export function GetSemanticStatus() {
  return window['go']['main']['App']['GetSemanticStatus']();
}

export function GetSidebarStats(arg1) {
  return window['go']['main']['App']['GetSidebarStats'](arg1);
}

export function GetTaskView(arg1, arg2) {
  return window['go']['main']['App']['GetTaskView'](arg1, arg2);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function IsInSemanticIndex(arg1) {
  return window['go']['main']['App']['IsInSemanticIndex'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function ProjectDeletionSummary(arg1) {
  return window['go']['main']['App']['ProjectDeletionSummary'](arg1);
}

export function RefreshEmbedding(arg1) {
  return window['go']['main']['App']['RefreshEmbedding'](arg1);
}

export function RemoveFromSemanticIndex(arg1) {
  return window['go']['main']['App']['RemoveFromSemanticIndex'](arg1);
}

export function RenameMeeting(arg1, arg2) {
  return window['go']['main']['App']['RenameMeeting'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function ReparentTask(arg1, arg2) {
  return window['go']['main']['App']['ReparentTask'](arg1, arg2);
}

export function SearchGlobal(arg1) {
  return window['go']['main']['App']['SearchGlobal'](arg1);
}

export function SearchSemantic(arg1) {
  return window['go']['main']['App']['SearchSemantic'](arg1);
}

export function SetMeetingHidden(arg1, arg2) {
  return window['go']['main']['App']['SetMeetingHidden'](arg1, arg2);
}

export function SetNoteHidden(arg1, arg2) {
  return window['go']['main']['App']['SetNoteHidden'](arg1, arg2);
}

export function SetProjectHidden(arg1, arg2) {
  return window['go']['main']['App']['SetProjectHidden'](arg1, arg2);
}

export function SetTaskDueDateQuick(arg1, arg2) {
  return window['go']['main']['App']['SetTaskDueDateQuick'](arg1, arg2);
}

export function TaskDeletionSummary(arg1) {
  return window['go']['main']['App']['TaskDeletionSummary'](arg1);
}

export function ToggleTaskCancelled(arg1) {
  return window['go']['main']['App']['ToggleTaskCancelled'](arg1);
}

export function ToggleTaskCompleted(arg1) {
  return window['go']['main']['App']['ToggleTaskCompleted'](arg1);
}

export function UpdateInstanceNotes(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceNotes'](arg1, arg2);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
