// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';
import {model} from '../models';
import {stats} from '../models';
import {notelayout} from '../models';

export function AddMeetingInstance(arg1:string):Promise<domain.MeetingInstance>;

export function AddToSemanticIndex(arg1:string,arg2:string):Promise<void>;

export function CreateMeeting(arg1:string,arg2:string):Promise<domain.Meeting>;

export function CreateNote(arg1:string,arg2:string):Promise<domain.Note>;

export function CreateProject(arg1:string):Promise<domain.Project>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<main.CreateTaskResult>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DeleteMeeting(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DissolveNoteGroup(arg1:string):Promise<void>;

export function GetAllTasks():Promise<Array<domain.Task>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetInstances(arg1:string):Promise<Array<domain.MeetingInstance>>;

export function GetMeetings(arg1:string):Promise<Array<domain.Meeting>>;

export function GetModelStatus():Promise<model.Status>;

export function GetNoteGroups(arg1:string):Promise<Array<domain.NoteGroup>>;

export function GetNotes(arg1:string):Promise<Array<domain.Note>>;

export function GetPriorityTasks():Promise<stats.PriorityTasks>;

export function GetSemanticStatus():Promise<main.SemanticStatus>;

export function GetSidebarStats(arg1:string):Promise<stats.SidebarStats>;

export function GetTaskView(arg1:string,arg2:main.FilterSelection):Promise<main.TaskView>;

export function GetTasks(arg1:string):Promise<Array<domain.Task>>;

export function GroupNotes(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.NoteGroup>;

export function IsInSemanticIndex(arg1:string):Promise<boolean>;

export function ListProjects():Promise<Array<domain.Project>>;

export function MoveTask(arg1:string,arg2:string):Promise<Array<domain.Task>>;

export function ProjectDeletionSummary(arg1:string):Promise<main.DeleteProjectSummary>;

export function RefreshEmbedding(arg1:string):Promise<void>;

export function RemoveFromSemanticIndex(arg1:string):Promise<void>;

export function RenameMeeting(arg1:string,arg2:string):Promise<domain.Meeting>;

export function RenameNoteGroup(arg1:string,arg2:string):Promise<domain.NoteGroup>;

export function RenameProject(arg1:string,arg2:string):Promise<domain.Project>;

export function ReparentTask(arg1:string,arg2:string):Promise<Array<domain.Task>>;

export function SearchGlobal(arg1:string):Promise<Array<main.SearchResult>>;

export function SearchSemantic(arg1:string):Promise<Array<main.SearchResult>>;

export function SetMeetingColor(arg1:string,arg2:string):Promise<domain.Meeting>;

export function SetMeetingHidden(arg1:string,arg2:boolean):Promise<domain.Meeting>;

export function SetNoteColor(arg1:string,arg2:string):Promise<domain.Note>;

export function SetNoteHidden(arg1:string,arg2:boolean):Promise<domain.Note>;

export function SetNotesLayout(arg1:string,arg2:Array<notelayout.Item>):Promise<void>;

export function SetProjectHidden(arg1:string,arg2:boolean):Promise<domain.Project>;

export function SetTaskDueDateQuick(arg1:string,arg2:string):Promise<domain.Task>;

export function TaskDeletionSummary(arg1:string):Promise<number>;

export function ToggleTaskCancelled(arg1:string):Promise<Array<domain.Task>>;

export function ToggleTaskCompleted(arg1:string):Promise<Array<domain.Task>>;

export function UpdateInstanceNotes(arg1:string,arg2:string):Promise<domain.MeetingInstance>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<domain.Note>;

export function UpdateTask(arg1:string,arg2:main.TaskPatch):Promise<domain.Task>;
